// UI components parameters in pixels

const FILE_FOLDER_PADDING = 19
const FILE_ICON_SIZE = 112
const MENUBAR_COMPLETE_HEIGHT = 80
const MENUBAR_SPLIT_HEIGHT = 64

export {
  FILE_FOLDER_PADDING,
  FILE_ICON_SIZE,
  MENUBAR_COMPLETE_HEIGHT,
  MENUBAR_SPLIT_HEIGHT,
}
